apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: vaultwarden
  namespace: manafishrov-vaultwarden
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vaultwarden
  serviceName: vaultwarden-internal
  template:
    metadata:
      labels:
        app: vaultwarden
    spec:
      containers:
        - name: vaultwarden
          image: vaultwarden/server:1.35.8
          envFrom:
            - secretRef:
                name: vaultwarden-env
          env:
            - name: SSO_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: manafishrov-tofu-outputs
                  key: vaultwarden_pocketid_client_id
            - name: SSO_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: manafishrov-tofu-outputs
                  key: vaultwarden_pocketid_client_secret
          ports:
            - containerPort: 80
              name: http
          livenessProbe:
            httpGet:
              path: /alive
              port: http
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /alive
              port: http
            periodSeconds: 10
          startupProbe:
            httpGet:
              path: /alive
              port: http
            periodSeconds: 10
            failureThreshold: 18
          volumeMounts:
            - mountPath: /data
              name: data
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi
        storageClassName: nvme-ha
