apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: roundcube-data-backup
  namespace: manafishrov-roundcube
spec:
  paused: true
  sourcePVC: data-roundcube-0
  trigger:
    schedule: "30 3 * * *"
  restic:
    repository: manata-restic-roundcube-pvc
    pruneIntervalDays: 36500
    retain:
      within: 100y
    moverSecurityContext:
      runAsUser: 33
      runAsGroup: 33
    copyMethod: Snapshot
    volumeSnapshotClassName: mayastor-snapshot
    cacheStorageClassName: openebs-single-replica
    cacheCapacity: 1Gi
