apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: roundcube
  namespace: manafishrov-roundcube
  annotations:
    configmap.reloader.stakater.com/reload: roundcube-config
    secret.reloader.stakater.com/reload: roundcube-env
spec:
  replicas: 1
  selector:
    matchLabels:
      app: roundcube
  serviceName: roundcube-internal
  template:
    metadata:
      labels:
        app: roundcube
    spec:
      containers:
        - name: roundcube
          image: roundcube/roundcubemail:1.7.1-apache@sha256:87aec514a46d915aad8e5c47a58024cdc4189de58b72d042c6cc6572d8b19417
          envFrom:
            - secretRef:
                name: roundcube-env
          ports:
            - containerPort: 80
              name: http
          livenessProbe:
            httpGet:
              path: /
              port: http
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /
              port: http
            periodSeconds: 10
          startupProbe:
            httpGet:
              path: /
              port: http
            periodSeconds: 10
            failureThreshold: 18
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              memory: 512Mi
          volumeMounts:
            - mountPath: /var/roundcube/config
              name: config
              readOnly: true
            - mountPath: /var/roundcube/db
              name: data
      volumes:
        - name: config
          configMap:
            name: roundcube-config
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 2Gi
        storageClassName: nvme-ha
