apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: roundcube
  namespace: manafishrov-roundcube
  annotations:
    configmap.reloader.stakater.com/reload: roundcube-config
    secret.reloader.stakater.com/reload: roundcube-env
spec:
  replicas: 1
  selector:
    matchLabels:
      app: roundcube
  serviceName: roundcube-internal
  template:
    metadata:
      labels:
        app: roundcube
    spec:
      containers:
        - name: roundcube
          image: roundcube/roundcubemail:1.7.2-apache@sha256:76503fb00caf1cb0ee7731723d5bf31b492383b689d532fa943c70e885913687
          envFrom:
            - secretRef:
                name: roundcube-env
          ports:
            - containerPort: 80
              name: http
          livenessProbe:
            httpGet:
              path: /
              port: http
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /
              port: http
            periodSeconds: 10
          startupProbe:
            httpGet:
              path: /
              port: http
            periodSeconds: 10
            failureThreshold: 18
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              memory: 512Mi
          volumeMounts:
            - mountPath: /var/roundcube/config
              name: config
              readOnly: true
            - mountPath: /var/roundcube/db
              name: data
      volumes:
        - name: config
          configMap:
            name: roundcube-config
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 2Gi
        storageClassName: nvme-ha
