apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - bulwark-preview.yaml
  - backup/replication-source.yaml
  - statefulset.yaml
  - services.yaml
  - httproute.yaml
  - dns.yaml
  - network-policy.yaml
  - config.yaml
